name: '@zju-health-report/action Demo'

on:
  workflow_dispatch:
  schedule:
    # `0 23 * * *` 表示UTC 23:00，即北京时间7:00打卡（经测试，实际运行时间比设定时间晚几分钟到几十分钟）。
    - cron: '0 23 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - username: ZJU_USERNAME_XIANG
            password: ZJU_PASSWORD_XIANG
            dingtalk_token: DINGTALK_TOKEN_XIANG
          - username: ZJU_USERNAME_NUO
            password: ZJU_PASSWORD_NUO
            dingtalk_token: DINGTALK_TOKEN_NUO
          - username: ZJU_USERNAME_KAI
            password: ZJU_PASSWORD_KAI
            dingtalk_token: DINGTALK_TOKEN_KAI
            # xiang doc
          - username: ZJU_USERNAME_DOC
            password: ZJU_PASSWORD_DOC
            dingtalk_token: DINGTALK_TOKEN_DOC
             # wang yw
          - username: ZJU_USERNAME_YW
            password: ZJU_PASSWORD_YW
            dingtalk_token: DINGTALK_TOKEN_YW
    steps:
      - name: 打卡
        uses: zju-health-report/action@release
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
        env:
          ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
